# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - redis_data:/data
  postgresql:
    image: docker.io/bitnami/postgresql:15
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=bitnami_gitea
      - POSTGRESQL_USERNAME=bn_gitea
      - POSTGRESQL_PASSWORD=bitnami1
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  gitea:
    image: quixanalytics/gitea:latest
    volumes:
      - 'gitea_data:/bitnami/gitea'
    environment:
      - GITEA_DATABASE_HOST=postgresql
      - GITEA_DATABASE_NAME=bitnami_gitea
      - GITEA_DATABASE_USERNAME=bn_gitea
      - GITEA_DATABASE_PASSWORD=bitnami1
      - GITEA_ADMIN_USER = admin
      - GITEA_ADMIN_PASSWORD = password
      - GITEA_QUEUE_CONN_STR=redis://redis:6379/0
      - GITEA_QUEUE_TYPE=redis
      # - GITEA_ISSUE_INDEXER_TYPE=db
      # - GITEA_SESSION_PROVIDER=db

    ports:
      - '3000:3000'
      - '2222:2222'
volumes:
  postgresql_data:
    driver: local
  gitea_data:
    driver: local
  redis_data:
    driver: local
